services:
  - type: web
    name: partseekr
    env: node
    plan: free
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: STRIPE_RESTRICTED_KEY
        sync: false
      - key: SITE_URL
        value: https://www.partseekr.online
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        value: '8542056338'
